name: Deploy to Docker Hub

on:
  push:
    branches:
      - master  # Trigger on push to the master branch
  workflow_dispatch:  # Allows manual trigger from the Actions tab

jobs:
  build-and-deploy:
    runs-on: self-hosted  # Use the self-hosted runner (optional)

    steps:
    # Step 1: Check out the repository
    - name: Check out the repository
      uses: actions/checkout@v2

    # Step 2: Log in to Docker Hub
    - name: Log in to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      shell: bash

    # Step 3: Build and push Docker image to Docker Hub
    - name: Build and push Docker image
      run: |
        # Build Docker image with tag using commit hash
        docker build -t sandeep1696/api_test:${{ github.sha }} .
        
        # Push Docker image to Docker Hub
        docker push sandeep1696/api_test:${{ github.sha }}
      shell: bash

    # Step 4: Deploy Docker container (optional)
    - name: Deploy to Docker container
      run: |
        docker run -d -p 80:80 --name api_test_${{ github.sha }} sandeep1696/api_test:${{ github.sha }}
      shell: bash

    # Step 5: Verify if the container is running (optional)
    - name: Verify Docker container
      run: |
        docker ps -a  # List all containers to verify the container is running
        docker logs api_test_${{ github.sha }}  # Show logs for the container
      shell: bash
