name: Deploy to Docker

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: self-hosted  # Use the self-hosted runner

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      shell: pwsh

    - name: Build and push Docker image
      run: |
        docker build -t sandeep1696/api_test:${{ github.sha }} .
        docker push sandeep1696/api_test:${{ github.sha }}
      shell: pwsh

    - name: Deploy to Docker container
      run: |
        docker run -d -p 80:80 sandeep1696/api_test:${{ github.sha }}
      shell: pwsh