name: Deploy to Docker Hub

on:
  push:
    branches:
      - master  # Change to 'main' if that's your default branch
  workflow_dispatch:  # For manual trigger

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # GitHub-hosted runner

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      run: |
        echo "${{ secrets.USER_PASSWORD_TOKEN }}" | docker login -u "${{ secrets.USER_NAME_DOCKER }}" --password-stdin
        docker info  # Verify Docker is set up correctly
      shell: bash

    - name: Build Docker image
      run: |
        docker build -t sandeep1696/api_test:${{ github.sha }} .
        docker images  # Verify the image was built
      shell: bash

    - name: Push Docker image to Docker Hub
      run: |
        docker push sandeep1696/api_test:${{ github.sha }}
      shell: bash

    - name: Deploy to Docker container (optional)
      run: |
        docker run -d -p 80:80 --name api_test_${{ github.sha }} sandeep1696/api_test:${{ github.sha }}
        docker ps  # Verify the container is running
      shell: bash
